name: PlotSigns
version: '${project.version}'
main: org.spooky.plotsigns.PlotSigns
api-version: '1.20'

commands:
  plotscan:
    description: Scans for all plots and signs
    usage: /plotscan
    permission: plotsigns.god

    plotscan:
      description: Release or Add user to plot
      usage: /plot
      permission: plotsigns.god
